# Generated by Django 2.1.7 on 2019-03-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userDOB', models.CharField(max_length=10)),
                ('userGender', models.CharField(max_length=6)),
                ('userBloodGroup', models.CharField(max_length=3)),
                ('userPhone', models.CharField(max_length=20)),
                ('userEmail', models.EmailField(max_length=100)),
                ('userAddress', models.CharField(max_length=500)),
                ('userImage', models.CharField(max_length=500)),
                ('userStatus', models.CharField(max_length=10)),
            ],
        ),
    ]
