# Generated by Django 2.1.7 on 2019-03-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190315_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionId', models.CharField(max_length=20)),
                ('candidateId', models.CharField(max_length=20)),
                ('candidateSign', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionTitle', models.CharField(max_length=200)),
                ('electionWinner', models.CharField(max_length=20)),
                ('electionStatus', models.BooleanField()),
            ],
        ),
    ]
