# Generated by Django 2.1.7 on 2019-03-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20190322_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='electionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Elections'),
        ),
        migrations.AlterField(
            model_name='elections',
            name='electionID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
