# Generated by Django 2.1.7 on 2019-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20190322_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='electionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
