# Generated by Django 2.1.7 on 2019-03-23 19:50

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20190324_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='electionId',
            field=models.ForeignKey(on_delete=django.db.models.fields.IntegerField, to='vote.Elections'),
        ),
    ]
