# Generated by Django 2.1.7 on 2019-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20190324_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='candidateEmail',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='candidateImage',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='candidateName',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='candidatePhone',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
