# Generated by Django 2.1.7 on 2019-03-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20190325_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(max_length=15)),
                ('electionId', models.IntegerField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
