# Generated by Django 2.1.7 on 2019-03-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
